services:
  video-watchdog:
    image: hexstan/video-watchdog:latest
    # build: .
    container_name: video-watchdog
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    
    volumes:
      # 配置文件和日志目录
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs

      # 需要监控和处理的目录
      - ./input:/app/input
      - ./output:/app/output
      - ./processed:/app/processed
    
    # 启用 Intel/AMD GPU 支持 (VAAPI/QSV)
    devices:
      - /dev/dri:/dev/dri
    # 启用 NVIDIA GPU 支持
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu, video, compute, utility]
